name: multi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.3
  intl: ^0.19.0
  pdf: ^3.10.4
  printing: ^5.13.1
  share_plus: ^7.2.2
  supabase_flutter: ^2.0.0+1
  cupertino_icons: ^1.0.6
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path: ^1.8.3
  path_provider: ^2.1.3
  formz: ^0.6.0
  flutter_hooks: ^0.19.0
  badges: ^2.0.3
  flutter_localizations:
    sdk: flutter
  
     
dev_dependencies:
  build_runner: ^2.4.11
  isar_generator: ^3.1.0 
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.6.1 
  awesome_snackbar_content: ^0.1.3
  flutter_image_compress: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images_multi/
    - assets/images_multi_compresed/
    - .env
